### ISSUE TITLE
Implement EVM type descriptors

### ISSUE THREAD

**Issue by kwannoel** [fare/gerbil-ethereum#49]
## TODOs

- [x] mstore
- [x] push
- [ ] (Stretch goal) Benchmark gas for methods
- [ ] memcpy
- [ ] mload tests
- [ ] mload implementation tweaks
- [ ] Integrate with EVM-Types
- [ ] Cleanup
    - [ ] Docs
    - [ ] Restructure tests? Should I leave type-descriptor tests in evm-eval-integrationtest?
- [ ] Invariant assertions
- [ ] Use brk
